version: '3.2'

networks:
  net:
    external:
      name: net  

services:  
  composer:
    image: hyperledger/fabric-tools:modded
    tty: true
    ports:
      - 3389:3389
    networks:
      net:
        aliases:
          - composer
    volumes:
      - type: volume
        source: nfs
        target: /srv/NFS
        volume:
          nocopy: true
    working_dir: /srv/NFS/composer
    deploy:
      placement:
        constraints: [node.role == manager]
#    command: /bin/bash -c './script.sh'
    

volumes:
  nfs:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS"    
