version: '3.2'

services:
  ca:
    image: hyperledger/fabric-ca:x86_64-1.0.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca
#      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/org1.example.com-cert.pem
#      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/a22daf356b2aab5792ea53e35f66fccef1d7f1aa2b3a2b92dbfbf96a448ea26a_sk
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.wgiplant.wgi.ap.mars-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/9dd3dfd5f9db9f07cdc9921e0081c9314c420d6f8c1921eb242c4c43af4cf118_sk -b admin:adminpw -d'
    volumes:
      - type: volume
        source: ca
        target: /etc/hyperledger/fabric-ca-server-config
        volume:
          nocopy: true
    networks: 
      - composer_default

  orderer:
    image: hyperledger/fabric-orderer:x86_64-1.0.4
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/composer-genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - type: volume
          source: orderer
          target: /etc/hyperledger/msp/orderer/msp
          volume:
            nocopy: true
        - type: volume
          source: tx
          target: /etc/hyperledger/configtx
          volume:
            nocopy: true
    networks:
      - composer_default

  peer0:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nfs_composer_default
      - CORE_PEER_LOCALMSPID=MarsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - type: volume
          source: tx
          target: /etc/hyperledger/configtx
          volume:
            nocopy: true
        - type: volume
          source: peer0MSP
          target: /etc/hyperledger/peer/msp
          volume:
            nocopy: true
        - type: volume
          source: peerUsers
          target: /etc/hyperledger/msp/users
          volume:
            nocopy: true
    depends_on:
      - orderer
      - couchdb0
    links:
      - orderer:orderer 
      - couchdb0:couchdb0
    networks:
      - composer_default

  
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:x86_64-1.0.4
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
    networks:
      - composer_default

networks: 
  composer_default:
    driver: bridge
    attachable: true

volumes:
  ca:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/wgiplant.wgi.ap.mars/ca/" 

  orderer:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/ordererOrganizations/wgiplant.wgi.ap.mars/orderers/orderer.wgiplant.wgi.ap.mars/msp/"  

  tx:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS"  

  peer0MSP:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/wgiplant.wgi.ap.mars/peers/peer0.wgiplant.wgi.ap.mars/msp"  

  peerUsers:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/wgiplant.wgi.ap.mars/users"  

  peer1MSP:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/wgiplant.wgi.ap.mars/peers/peer1.wgiplant.wgi.ap.mars/msp"  

  crypto:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config"  
