version: '3.2'

networks:
  net:
    external:
      name: net  

services:  
  couchdb0:
    image: hyperledger/fabric-couchdb:x86_64-1.0.4
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
    networks:
      net:
        aliases:
          - couchdb0

  couchdb1:
    image: hyperledger/fabric-couchdb:x86_64-1.0.4
    ports:
      - 6984:5984
    environment:
      DB_URL: http://localhost:6984/member_db
    networks:
      net:
        aliases:
          - couchdb1