version: '3.2'
networks:
  net:
    external:
      name: net
services:
  peer0:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    dns_search: .
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0
      - CORE_PEER_ADDRESS=peer_peer0:7051    
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
      - CORE_PEER_LOCALMSPID=MarsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch_couchdb0:5984
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@example.com/msp
    working_dir: /etc/hyperledger/configtx
    command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - /var/run/docker.sock:/var/run/docker.sock
        - type: volume
          source: tx
          target: /etc/hyperledger/configtx
          volume:
            nocopy: true
        - type: volume
          source: peer0MSP
          target: /etc/hyperledger/peer/msp
          volume:
            nocopy: true
        - type: volume
          source: peerUsers
          target: /etc/hyperledger/msp/users
          volume:
            nocopy: true
    networks:
      net:
        aliases:
          - peer0
    deploy:
      placement:
        constraints: [node.role == manager]

  peer1:
    image: hyperledger/fabric-peer:x86_64-1.0.4
    dns_search: .
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer1
      - CORE_PEER_ADDRESS=peer_peer1:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
      - CORE_PEER_LOCALMSPID=MarsMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couch_couchdb1:5984
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@example.com/msp
    working_dir: /etc/hyperledger/configtx
    command: peer node start --peer-defaultchain=false
    ports:
      - 7081:7051
      - 7083:7053
    volumes:
        - /var/run/:/host/var/run/
        - /var/run/docker.sock:/var/run/docker.sock
        - type: volume
          source: tx
          target: /etc/hyperledger/configtx
          volume:
            nocopy: true
        - type: volume
          source: peer1MSP
          target: /etc/hyperledger/peer/msp
          volume:
            nocopy: true
        - type: volume
          source: peerUsers
          target: /etc/hyperledger/msp/users
          volume:
            nocopy: true
    networks:
      net:
        aliases:
          - peer1
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:

  tx:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS"  

  peer0MSP:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/example.com/peers/peer0.example.com/msp"  

  peerUsers:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/example.com/users"  

  peer1MSP:
    driver_opts:
      type: "nfs"
      o: "addr=10.140.20.189,nolock,soft,rw"
      device: ":/srv/NFS/crypto-config/peerOrganizations/example.com/peers/peer1.example.com/msp"  

